default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  user: postgres
  password:  <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: store-stock-management_development

test:
  <<: *default
  database: store-stock-management_test

production:
  <<: *default
  database: store-stock-management_production